version: '3.9'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "3003:3003"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend-app
    ports:
      - "3004:3000"
    depends_on:
      - backend
