name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout du repo
        uses: actions/checkout@v3

      - name: 2. Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 3. Installation des dépendances
        run: |
          cd frontend
          npm install

      - name: 4. Lancement des tests
        run: |
          cd frontend
          npm test

      - name: 5. Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-management-app:latest .

      - name: 6. Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 7. Push de l'image vers Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/user-management-app:latest

      # - name: 8. (Optionnel) Déploiement via SSH
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       docker pull ${{ secrets.DOCKER_USERNAME }}/user-management-app:latest
      #       docker stop frontend-app || true
      #       docker rm frontend-app || true
      #       docker run -d -p 3000:3000 --name frontend-app ${{ secrets.DOCKER_USERNAME }}/user-management-app:latest
