name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout du repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 3. Installation des dépendances
    - name: Install dependencies
      run: npm install
      working-directory: ./frontend

    # 4. Lancement des tests
    - name: Run tests
      run: npm test --if-present
      working-directory: ./frontend

    # 5. Build Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/user-management-app:latest .

    # 6. Login Docker Hub
    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # 7. Push Docker image
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/user-management-app:latest

    # 8. (Optionnel) Déploiement via SSH
    - name: Deploy via SSH
      if: ${{ secrets.SSH_HOST != '' }}
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/user-management-app:latest
          docker stop app || true
          docker rm app || true
          docker run -d --name app -p 3003:3003 ${{ secrets.DOCKER_USERNAME }}/user-management-app:latest
